# Slicing In Numpy

### One dimensional 

In [3]:
import numpy as np

In [7]:
list1 = [1,2,3,4,5,6,7,8,9]
list1[1:3:]

[2, 3]

In [8]:
array1 = np.array(list1)

In [9]:
array1[1:7:2]

array([2, 4, 6])

### Multi Dimensional

In [18]:
list2 = [[1,2,3,4,5,6,7,8], [1,3,5,7,9,11,13,15]]

In [20]:
list2[0][5:9]

[6, 7, 8]

In [21]:
array2 = np.array(list2)

In [25]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [56]:
arr1 = [i[1::2] for i in array2] #using loop for slicing
#arr2 = [i[0::2] for i in array2]
arr1
#arr2


[array([2, 4, 6, 8]), array([ 3,  7, 11, 15])]

In [43]:
array2[:,1::2]

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

In [23]:
array2[0][5:]

array([6, 7, 8])

In [24]:
array2[0,5:]

array([6, 7, 8])

In [49]:
list3 = [[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15],[15,25,9999,376,19,420,786,555]]

In [50]:
array3 = np.array(list3)

In [51]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [55]:
array3[1:,4:7:1]

array([[  9,  11,  13],
       [ 19, 420, 786]])

In [66]:
array3.shape

(3, 8)

In [70]:
list4 = [
    [[1,2,3,4], [5,6,7,8]],
    [[1,3,5,7],[9,11,13,15]],
    [[15,25,9999,376],[19,420,786,555]]
        ]

In [71]:
array4 = np.array(list4)

In [72]:
array4.shape

(3, 2, 4)

In [74]:
array4.ndim

3

In [75]:
array4[:2,:,1:3]

array([[[ 2,  3],
        [ 6,  7]],

       [[ 3,  5],
        [11, 13]]])