# Numpy


In [1]:
import numpy as np

## Creating Numpy Arrays

### np.array() 
#### To convert list to array

In [5]:
#One dimensional array
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim) #To check the dimension of array

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
1


In [7]:
# multidimensional array
list2 = [[1,2], [3,4]]
print(type(list2))
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)


<class 'list'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


### np.Zeros()

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3)) #the no. inside the tupple determine the dimension as it has 2 values its a 2 dimensional array. 
#(2,3) = 2rows and 3 column
                #

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.zeros((2,3,4))
print(arr)
print(arr.ndim)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


### np.ones()

In [12]:
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.full()

In [24]:
np.full(5,-2) #it automaticall fill the given no = 2 in all 5 column of array

array([-2, -2, -2, -2, -2])

In [25]:
np.full((2,3), -2) #it 

array([[-2, -2, -2],
       [-2, -2, -2]])

### np.arange()

In [29]:
# np.array(range(start, stop, step))
# this only works in one diminsional array
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(2,10,2)

array([2, 4, 6, 8])

### np.linspace()

In [40]:
#np.linspace(start, stop, num_of_element_in_between)

np.linspace(1,10,2) #this helps to make evenly space element

array([ 1., 10.])

In [41]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
np.linspace((1,2),(5,10), num=5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

### np.diag()

In [43]:
np.diag([2,3,4,5]) #it always works in square metrices

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [44]:
np.diag([2,3,4,5], k=1)

array([[0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [45]:
np.diag([2,3,4,5], k= -1) #this preserv value as well position of it and changes dimension

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0]])

### np.eye()

In [49]:
#this gives identity metrix
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(5, k=-1) #this preserve the dimension but changes the value and position of it

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### np.identity()

In [54]:
#this also gives identity metrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random.rand()

In [58]:
np.random.rand(2)

array([0.62425761, 0.93403312])

In [59]:
np.random.rand(2,3)


array([[1.82308693, 1.44272376, 0.95258687],
       [0.29561219, 0.33592872, 0.68951791]])

In [60]:
np.random.rand(2,3,4)*2 #Scalar multiplication

array([[[0.90323292, 0.48996717, 0.37111339, 0.32207082],
        [0.55586195, 0.2025352 , 1.05162962, 1.19410476],
        [0.50575115, 1.98911506, 0.86284428, 1.48122539]],

       [[1.59904664, 0.18866772, 1.21055635, 0.46378385],
        [1.17337757, 0.69131169, 0.50679724, 1.95602859],
        [0.29546299, 1.69248518, 1.45592375, 1.85883207]]])

### np.random.randint()

In [70]:
np.random.randint(2,7,size=(2,3)) #(start,stop,dimension)

array([[5, 2, 5],
       [2, 6, 3]])