# Array Operation

### Elament Wise Operation

In [9]:
import numpy as np

In [10]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7]])

In [11]:
a

array([[4, 5, 6],
       [5, 7, 9]])

In [12]:
b

array([[1, 2, 3],
       [9, 8, 7]])

In [13]:
a+b

array([[ 5,  7,  9],
       [14, 15, 16]])

In [14]:
a-b

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [15]:
a*b

array([[ 4, 10, 18],
       [45, 56, 63]])

In [16]:
c = np.array([[4,5],[7,9]])
d = np.array([[1,2,3],[9,8,7]])
f = np.multiply(c,d)
f

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### Metrix Operation

In [17]:
h = np.array([[4,5],[5,7]])
i = np.array([[1,2],[9,8]])


In [18]:
h

array([[4, 5],
       [5, 7]])

In [19]:
i

array([[1, 2],
       [9, 8]])

In [20]:
np.cross(h,i)

array([  3, -23])

In [21]:
np.dot(h,i)

array([[49, 48],
       [68, 66]])

In [22]:
j = np.array([[4,5,7],[5,7,9]])
k = np.array([[1,2],[9,8]])

In [23]:
np.dot(j,k)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [24]:
np.dot(k,j)

array([[ 14,  19,  25],
       [ 76, 101, 135]])

In [25]:
np.transpose(j) #change row to column and column to row 

array([[4, 5],
       [5, 7],
       [7, 9]])

In [26]:
np.trace(k) #it gives the sum og diagnol element of metrix and diagnol metrix is always same in sqr metrix

9

In [27]:
np.linalg.det(k)

-10.000000000000002

In [28]:
np.linalg.det(j) #Last 2 dimensions of the array must be square as non-sqr metrix doenst give determinant

LinAlgError: Last 2 dimensions of the array must be square

In [29]:
np.linalg.inv(k)

array([[-0.8,  0.2],
       [ 0.9, -0.1]])

In [30]:
np.linalg.eig(k)

(array([-1., 10.]),
 array([[-0.70710678, -0.21693046],
        [ 0.70710678, -0.97618706]]))

In [31]:
a = [[1,2],[3,5]]
b = [1,2]
np.linalg.solve(a,b) #its as same as metric multiplication as in np.dot() so (1*2)

array([-1.,  1.])

### Broadcasting

In [32]:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

In [33]:
a

array([[1, 2],
       [3, 5]])

In [34]:
b

array([1, 2])

In [35]:
a+b #it broadcat or clone like ([[1,2],[1,2]) as much as it needs for the needed operation

array([[2, 4],
       [4, 7]])

### Why Numpy over Python For loop

In [36]:
import numpy as np
import time

# Using Numpy for element-wise multiplication
a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
c = a*b
end = time.time()
numpy_execuation_time = end - start
print("Time taken by Numpy: {:.6f} seconds".format(numpy_execuation_time))

# Using Python for loop for element-wise multiplication
a = list(a)
b= list(b)
c = []

start = time.time()
for i in range(len(a)):
    c.append(a[i]*b[i])
end = time.time()
for_loop_execuation_time = end-start
print("Time taken by Python for Loop: {:.6f} seconds".format(end-start))

print(f'Numpy is {int(for_loop_execuation_time/numpy_execuation_time)} times faster than Python')

Time taken by Numpy: 0.005005 seconds
Time taken by Python for Loop: 0.446049 seconds
Numpy is 89 times faster than Python


### Boolean-Mask- Indexing

In [37]:
a = np.array([[1,2],[3,4],[5,6]])
mask = np.array([True, False, True])


In [39]:
b = a[mask]
print(b)

[[1 2]
 [5 6]]


In [40]:
mask = np.array([[True,False],[True,False],[True,False]])


In [41]:
a[mask]

array([1, 3, 5])

In [43]:
mask = np.array([[True,False],True,[True,False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [46]:
mask = np.array([[True,False],[True],[True,False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

#### condition Masking
  It helps to slove the error given by dimension/shape as seen above

In [47]:
a = np.array([[1,2],[3,4],[5,6]])
mask = (a > 2)


In [48]:
a[mask]

array([3, 4, 5, 6])