In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a.shape #its a numpy attribute

(2, 3)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

2

In [6]:
a.flatten() #it changes metrix into list according to its arrangement and dimension

array([1, 2, 3, 4, 5, 6])

In [7]:
list4 = [
    [[1,2,3,4], [5,6,7,8]],
    [[1,3,5,7],[9,11,13,15]],
    [[15,25,9999,376],[19,420,786,555]]
        ]

In [10]:
array1 = np.array(list4)

In [11]:
array1.flatten()

array([   1,    2,    3,    4,    5,    6,    7,    8,    1,    3,    5,
          7,    9,   11,   13,   15,   15,   25, 9999,  376,   19,  420,
        786,  555])

In [12]:
a.sum() #it gives the sum of the metrix

21

In [17]:
print(a.max())#it gives maximum value from a metrix
print(a.max(axis=0)) #it gives max value accour to column no.
print(a.max(axis=1))#it gives max value according to row

6
[4 5 6]
[3 6]


In [18]:
a.argmax(axis=1) #it gives max value of 

array([2, 2], dtype=int64)

In [19]:
a.shape

(2, 3)

In [20]:
#Note: Product of element should be conserved
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
b = a.reshape((1,2,3))

In [25]:
b.shape

(1, 2, 3)

In [26]:
# Concatinate
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])

In [27]:
np.concatenate((m, n), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
print(np.concatenate((m,n), axis=1))#it preserve row
print(np.concatenate((m,n), axis=0)) #it preserve column

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
c = a.reshape(6)
c

array([1, 2, 3, 4, 5, 6])

In [47]:
string = "hello how are you"

In [48]:
string.split(' ')

['hello', 'how', 'are', 'you']

In [49]:
np.split(c,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [52]:
np.split(c, [2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]