# Type And Type Conversion

In [11]:
import numpy as np

a = np.array([1,2,3], dtype = np.int32) #create an array of interger with 32bit memory size
b = np.array([1.0,2.0,3.0], dtype = np.float64)
c= np.array([True, False, True], dtype = np.bool_)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
bool


In [12]:
d = np.array([1,2,3], dtype = np.float64)
d

array([1., 2., 3.])

In [13]:
e = np.array([1.0,2.0,3.0], dtype = np.int32)
e

array([1, 2, 3])

In [14]:
f= np.array([True, False, True], dtype = np.int32)
f


array([1, 0, 1])

## Type Conversion

### astype()

In [15]:
a.dtype

dtype('int32')

In [17]:
g = a.astype(np.float32)

In [18]:
g

array([1., 2., 3.], dtype=float32)